remove version check from PyPI deployment

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -151,23 +151,23 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
-        python-version: "3.9"
+        python-version: "3.12"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install wheel twine
-    - name: Check the tag
-      run: |
-        PACKAGE_VERSION=`python setup.py --version`
-        TAG_NAME=v$PACKAGE_VERSION
-        echo "Package version $PACKAGE_VERSION with possible tag name $TAG_NAME on $GITHUB_REF_NAME"
-        # test that the tag represents the version
-        # see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
-        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables
-        if [ "$TAG_NAME" != "$GITHUB_REF_NAME" ]; then
-          echo "ERROR: This tag is for the wrong version. Got \"$GITHUB_REF_NAME\" expected \"$TAG_NAME\"."
-          exit 1
-        fi
+#    - name: Check the tag
+#      run: |
+#        PACKAGE_VERSION=`python setup.py --version`
+#        TAG_NAME=v$PACKAGE_VERSION
+#        echo "Package version $PACKAGE_VERSION with possible tag name $TAG_NAME on $GITHUB_REF_NAME"
+#        # test that the tag represents the version
+#        # see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
+#        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables
+#        if [ "$TAG_NAME" != "$GITHUB_REF_NAME" ]; then
+#          echo "ERROR: This tag is for the wrong version. Got \"$GITHUB_REF_NAME\" expected \"$TAG_NAME\"."
+#          exit 1
+#        fi
     - name: remove old files
       run: rm -rf dist/*
     - name: build distribution files
