Add languages automatically to documentation once they are translated

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -27,6 +27,8 @@ jobs:
         run: pip install tox
       - name: Build the documentation
         run: tox -e docs -- build
+      - name: Add missing languages
+        run: ./scripts/find-translated-documentation-languages.sh
       - name: Check status
         run: git status
       - name: Push updates translation files
@@ -35,5 +37,7 @@ jobs:
           git config --global user.email 'owc-github-actions@users.noreply.github.com'
           git add translations
           if git commit -m "Update translation files"; then
-            git push
+            if ! git push; then
+              echo "ERROR: Push failed."
+            fi
           fi
